### ISSUE TITLE
feat: product price

### ISSUE THREAD

**Issue by Minhquanzz1002** [Minhquanzz1002/cinema-api#50]
# Tasks

- [ ] API: list product price
- [ ] API: create product price
- [ ] API: update product price
- [ ] API: delete product price
